version: 2

sources:
  - name: raw_data
    description: raw data for nyc taxi rides
    database: taxi_rides_ny
    schema: prod
    tables:
      - name: yellow_tripdata
        description: raw yellow taxi trip data
        columns:
          - name: vendorid
            description: "Taxi technology provider (1 = Creative Mobile Technologies, 2 = VeriFone Inc.) - Note: Raw data may contain nulls, filtered in staging"
          - name: tpep_pickup_datetime
            description: Date and time when the meter was engaged
          - name: tpep_dropoff_datetime
            description: Date and time when the meter was disengaged
          - name: passenger_count
            description: Number of passengers in the vehicle
          - name: trip_distance
            description: Trip distance in miles
          - name: pulocationid
            description: TLC Taxi Zone where the meter was engaged
          - name: dolocationid
            description: TLC Taxi Zone where the meter was disengaged
          - name: ratecodeid
            description: Rate code (1=Standard, 2=JFK, 3=Newark, 4=Nassau/Westchester, 5=Negotiated, 6=Group)
          - name: store_and_fwd_flag
            description: Trip record held in vehicle memory (Y/N)
          - name: payment_type
            description: Payment method (1=Credit card, 2=Cash, 3=No charge, 4=Dispute, 5=Unknown, 6=Voided)
          - name: fare_amount
            description: Time and distance fare
          - name: extra
            description: Miscellaneous extras and surcharges
          - name: mta_tax
            description: MTA tax
          - name: tip_amount
            description: Tip amount (credit card only)
          - name: tolls_amount
            description: Total tolls paid
          - name: improvement_surcharge
            description: Improvement surcharge
          - name: total_amount
            description: Total amount charged

      - name: green_tripdata
        description: raw green taxi trip data
        columns:
          - name: vendorid
            description: "Taxi technology provider (1 = Creative Mobile Technologies, 2 = VeriFone Inc.) - Note: Raw data may contain nulls, filtered in staging"
          - name: lpep_pickup_datetime
            description: Date and time when the meter was engaged
          - name: lpep_dropoff_datetime
            description: Date and time when the meter was disengaged
          - name: passenger_count
            description: Number of passengers in the vehicle
          - name: trip_distance
            description: Trip distance in miles
          - name: pulocationid
            description: TLC Taxi Zone where the meter was engaged
          - name: dolocationid
            description: TLC Taxi Zone where the meter was disengaged
          - name: ratecodeid
            description: Rate code (1=Standard, 2=JFK, 3=Newark, 4=Nassau/Westchester, 5=Negotiated, 6=Group)
          - name: store_and_fwd_flag
            description: Trip record held in vehicle memory (Y/N)
          - name: payment_type
            description: Payment method (1=Credit card, 2=Cash, 3=No charge, 4=Dispute, 5=Unknown, 6=Voided)
          - name: fare_amount
            description: Time and distance fare
          - name: extra
            description: Miscellaneous extras and surcharges
          - name: mta_tax
            description: MTA tax
          - name: tip_amount
            description: Tip amount (credit card only)
          - name: tolls_amount
            description: Total tolls paid
          - name: improvement_surcharge
            description: Improvement surcharge
          - name: total_amount
            description: Total amount charged
          - name: trip_type
            description: Trip type (1=Street-hail, 2=Dispatch)
          - name: ehail_fee
            description: E-hail fee

      - name: fhv_tripdata
        description: raw fhv taxi trip data
        columns:
          - name: dispatching_base_num
            description: Dispatching base number
          - name: pickup_datetime
            description: Date and time when the meter was engaged
          - name: dropoff_datetime
            description: Date and time when the meter was disengaged
          - name: pulocationid
            description: TLC Taxi Zone where the meter was engaged
          - name: dolocationid
            description: TLC Taxi Zone where the meter was disengaged
          - name: SR_Flag
            description: Shared ride flag (Y/N)
          - name: affiliated_base_number
            description: Affiliated base number